name: EdenMCWelcome
version: ${project.version}
main: fr.steven.edenmcwelcome.EdenMCWelcome
api-version: 1.16
description: Simple minecraft plugin that allow users to welcome new players
commands:
  b:
    description: Welcome a new player
